source 'http://rubygems.org'

gem 'rails', '~> 3.2.21'
gem 'mailboxer', :path => '../../'
gem 'factory_girl'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'bson_ext'
gem "mongoid", "~> 3.0.0"

# send email
group :development do
  gem 'mailcatcher', '0.5.10'
end

