source 'http://rubygems.org'

gem 'rails', '4.0.0'
gem 'mailboxer', :path => '../../'
gem 'factory_girl'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'bson'
gem "mongoid", ">= 4.0"
